seed: 42
episodes: 1000
total_steps: null  # Alternative to episodes - use either episodes OR total_steps
buffer_size: 50000
batch_size: 256
gamma: 0.99
tau: 0.005
actor_lr: 0.001
critic_lr: 0.001
noise_sigma: 0.3
noise_clip: 0.7
policy_delay: 2
warmup_steps: 1000
save_every_episodes: 10  # Save a checkpoint every N episodes (0 to disable)

# Environment settings
map: 6

# Past states for temporal awareness
past_states:
  enabled: false  # Enable past state augmentation
  source: "wheels"  # "wheels" or "sensors" - wheel outputs are more concise 
  count: 8  # Number of past states to include
  stride: 5  # Stride between past states (e.g., t-3, t-6, t-9, t-12 if stride=3)
